FROM node:latest

RUN npm install -g nodemon
RUN npm install -g ts-node

WORKDIR /app
RUN chown -R node /app
USER node

CMD ["cd code", "&&", "yarn", "&&", "nodemon", "app.ts"]

ENV SITE_INSTANCE=dev
EXPOSE 8000