services:
  tv-app:
    container_name: tv-chart
    image: tv-chart
    ports:
      - target: 8000
        published: 8000
    volumes:
      - type: volume
        source: tv-chart-data
        target: /app/data

volumes:
  tv-chart-data:
