services:
  tv-app:
    container_name: tv-chart-dev
    image: tv-chart-dev
    ports:
      - target: 8000
        published: 8000
    volumes:
      - type: bind
        source: ./data
        target: /app/data
      - type: bind
        source: ./code
        target: /app/code
